name: app_module
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.5.1

  #dio
  dio: ^4.0.1

  #loading network image
  cached_network_image: ^3.2.0

  #flutter_slidable
  flutter_slidable: ^1.1.0

  #shared_preferences
  shared_preferences: ^2.0.8

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: NunitoSans
      fonts:
        - asset: "assets/fonts/NunitoSans-Light.ttf"
          weight: 300
        - asset: "assets/fonts/NunitoSans-Regular.ttf"
          weight: 400
        - asset: "assets/fonts/NunitoSans-SemiBold.ttf"
          weight: 600
        - asset: "assets/fonts/NunitoSans-Bold.ttf"
          weight: 700
